name: App

on: [push]

jobs:
  setup:
    name: Build and Runs tests
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.4'
      - uses: actions/checkout@v3
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Create SQLite database
        run: |
          mkdir -p database
          touch database/database.sqlite
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate App key
        run: php artisan key:generate
      - name: Generate JWT secret key
        run: php artisan jwt:secret --force
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
#      - name: Execute lint via Pint
#        run: vendor/bin/pint --test
      - name: Execute Unit tests
        run: php artisan test --testsuite=Unit
      - name: Execute Feature tests
        run: php artisan test --testsuite=Feature
